# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Backend build

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore ClassManagementWebAPI/ClassManagementWebAPI/ClassManagementWebAPI.csproj
    - name: Build
      run: dotnet build --no-restore ClassManagementWebAPI/ClassManagementWebAPI/ClassManagementWebAPI.csproj
#    Uncomment this when tests are added      
#    - name: Test
#      run: dotnet test --no-build --verbosity normal ClassManagementWebAPI/ClassManagementWebAPI/ClassManagementWebAPI.csproj
